sudo: false
language: python
python:
    - "3.5"
cache:
    directories:
        - $HOME/.cache/pip
install:
    - pip install -r requirements.txt
    - pip install flake8 coverage coveralls
script:
    - flake8 --exclude=migrations gallery/gallery
after_success:
    - coverage report
    - coveralls
