# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='title',
            field=models.CharField(default='(unknown)', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='collection',
            unique_together=set([('owner', 'title')]),
        ),
    ]
