# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 17:01
from __future__ import unicode_literals

import datetime
from django.db import migrations
from django.utils.timezone import utc
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_auto_20160515_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 15, 17, 1, 8, 577713, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collection',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 15, 17, 1, 12, 720204, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
