# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0005_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='collections',
            field=models.ManyToManyField(to='media.Collection'),
        ),
    ]
