# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0006_item_collections'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='content_meta',
            field=models.TextField(blank=True, null=True),
        ),
    ]
