# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 21:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0008_share'),
    ]

    operations = [
        migrations.RenameField(
            model_name='share',
            old_name='user',
            new_name='owner',
        ),
    ]
