# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0009_auto_20160515_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='status',
            field=models.CharField(choices=[('a', 'Active'), ('i', 'Inactive'), ('r', 'Removed')], default='a', max_length=1),
        ),
    ]
