# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-15 22:00
from __future__ import unicode_literals

from django.db import migrations
import taggit_machinetags.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit_machinetags', '0001_initial'),
        ('media', '0010_share_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='tags',
            field=taggit_machinetags.managers.MachineTaggableManager(help_text='A comma-separated list of tags.', through='taggit_machinetags.MachineTaggedItem', to='taggit_machinetags.MachineTag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='item',
            name='tags',
            field=taggit_machinetags.managers.MachineTaggableManager(help_text='A comma-separated list of tags.', through='taggit_machinetags.MachineTaggedItem', to='taggit_machinetags.MachineTag', verbose_name='Tags'),
        ),
    ]
