# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0011_auto_20160515_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='share_type',
            field=models.CharField(choices=[('p', 'Public'), ('l', 'With link'), ('s', 'With Password'), ('a', 'With Account')], default='l', max_length=1),
        ),
    ]
