# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0012_share_share_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
